/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0Om8UpLNCP8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function testtwo() {
  return (
    (<div className="flex h-screen bg-gray-100">
      <aside className="w-64 border-r bg-white">
        <div className="flex items-center justify-center h-16 border-b">
          <h1 className="text-lg font-semibold">Alicia Koch</h1>
        </div>
        <nav className="p-2">
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <InboxIcon className="w-5 h-5 text-gray-600" />
            <span>Inbox</span>
            <Badge variant="secondary">128</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <DraftingCompassIcon className="w-5 h-5 text-gray-600" />
            <span>Drafts</span>
            <Badge variant="secondary">9</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <SendIcon className="w-5 h-5 text-gray-600" />
            <span>Sent</span>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <TrashIcon className="w-5 h-5 text-gray-600" />
            <span>Junk</span>
            <Badge variant="secondary">23</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <TrashIcon className="w-5 h-5 text-gray-600" />
            <span>Trash</span>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <ArchiveIcon className="w-5 h-5 text-gray-600" />
            <span>Archive</span>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <FacebookIcon className="w-5 h-5 text-gray-600" />
            <span>Social</span>
            <Badge variant="secondary">972</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <ReplaceIcon className="w-5 h-5 text-gray-600" />
            <span>Updates</span>
            <Badge variant="secondary">342</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <FlagIcon className="w-5 h-5 text-gray-600" />
            <span>Forums</span>
            <Badge variant="secondary">128</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <ShoppingCartIcon className="w-5 h-5 text-gray-600" />
            <span>Shopping</span>
            <Badge variant="secondary">8</Badge>
          </a>
          <a
            className="flex items-center p-2 space-x-3 rounded hover:bg-gray-100"
            href="#">
            <PresentationIcon className="w-5 h-5 text-gray-600" />
            <span>Promotions</span>
            <Badge variant="secondary">21</Badge>
          </a>
        </nav>
      </aside>
      <main className="flex-1">
        <div className="flex h-16 items-center px-4 border-b">
          <Input className="flex-1" placeholder="Search" type="search" />
        </div>
        <div className="flex flex-1">
          <div className="w-80 border-r">
            <ScrollArea className="p-2 space-y-2">
              <Card className="bg-gray-200">
                <CardHeader>
                  <CardTitle>William Smith</CardTitle>
                  <CardDescription>Meeting Tomorrow</CardDescription>
                </CardHeader>
                <CardContent>
                  Hi, Let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and
                  have some ideas I'd like to share. It's crucial that we align on our...
                </CardContent>
                <CardFooter className="flex justify-between">
                  <Badge variant="default">meeting</Badge>
                  <Badge variant="secondary">work</Badge>
                  <Badge variant="secondary">important</Badge>
                </CardFooter>
              </Card>
            </ScrollArea>
          </div>
          <div className="flex-1 p-4">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-semibold">William Smith</h2>
              <div className="flex space-x-2">
                <ReplyIcon className="w-5 h-5 text-gray-600" />
                <ForwardIcon className="w-5 h-5 text-gray-600" />
                <MoveVerticalIcon className="w-5 h-5 text-gray-600" />
              </div>
            </div>
            <div className="mt-2 mb-4 text-sm text-gray-500">Oct 22, 2023, 9:00:00 AM</div>
            <div className="mb-4">
              <div className="flex items-center space-x-2">
                <Avatar>
                  <AvatarImage alt="William Smith" src="/placeholder.svg?height=40&width=40" />
                  <AvatarFallback>WS</AvatarFallback>
                </Avatar>
                <span className="font-semibold">William Smith</span>
                <span className="text-gray-500">Meeting Tomorrow</span>
              </div>
              <div className="mt-1 text-sm text-gray-500">Reply-To: williamsmith@example.com</div>
            </div>
            <div className="mb-4">
              <p>
                Hi, let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and
                have some ideas I'd like to share. It's crucial that we align on our next steps to ensure the project's
                success.
              </p>
              <p>Please come prepared with any questions or insights you may have. Looking forward to our meeting!</p>
              <p>Best regards, William</p>
            </div>
            <div className="flex items-center justify-between">
              <Button variant="outline">Mute this thread</Button>
              <Button>Send</Button>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}

function ArchiveIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="5" x="2" y="3" rx="1" />
      <path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8" />
      <path d="M10 12h4" />
    </svg>)
  );
}


function DraftingCompassIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="5" r="2" />
      <path d="m3 21 8.02-14.26" />
      <path d="m12.99 6.74 1.93 3.44" />
      <path d="M19 12c-3.87 4-10.13 4-14 0" />
      <path d="m21 21-2.16-3.84" />
    </svg>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function FlagIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>)
  );
}


function ForwardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="15 17 20 12 15 7" />
      <path d="M4 18v-2a4 4 0 0 1 4-4h12" />
    </svg>)
  );
}


function InboxIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="22 12 16 12 14 15 10 15 8 12 2 12" />
      <path
        d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z" />
    </svg>)
  );
}


function MoveVerticalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="8 18 12 22 16 18" />
      <polyline points="8 6 12 2 16 6" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>)
  );
}


function PresentationIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 3h20" />
      <path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3" />
      <path d="m7 21 5-5 5 5" />
    </svg>)
  );
}


function ReplaceIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14 4c0-1.1.9-2 2-2" />
      <path d="M20 2c1.1 0 2 .9 2 2" />
      <path d="M22 8c0 1.1-.9 2-2 2" />
      <path d="M16 10c-1.1 0-2-.9-2-2" />
      <path d="m3 7 3 3 3-3" />
      <path d="M6 10V5c0-1.7 1.3-3 3-3h1" />
      <rect width="8" height="8" x="2" y="14" rx="2" />
    </svg>)
  );
}


function ReplyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="9 17 4 12 9 7" />
      <path d="M20 18v-2a4 4 0 0 0-4-4H4" />
    </svg>)
  );
}


function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}


function ShoppingCartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path
        d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
