/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ItK87A8XrJ8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function testthree() {
  return (
    (<div className="flex h-screen bg-gray-100">
      <aside className="w-64 border-r bg-white">
        <div className="flex items-center justify-center h-16 border-b">
          <h1 className="text-lg font-semibold">Alicia Koch</h1>
        </div>
        <nav className="p-4">
          <ul>
            <li
              className="flex items-center justify-between p-2 text-blue-600 bg-blue-100 rounded-md">
              <span>Inbox</span>
              <span className="px-2 py-1 text-sm text-white bg-blue-600 rounded-full">128</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Drafts</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">9</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Sent</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Junk</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">23</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Trash</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Archive</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Social</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">972</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Updates</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">342</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Forums</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">128</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Shopping</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">8</span>
            </li>
            <li
              className="flex items-center justify-between p-2 mt-2 hover:bg-gray-100 rounded-md">
              <span>Promotions</span>
              <span className="px-2 py-1 text-sm text-gray-700 bg-gray-200 rounded-full">21</span>
            </li>
          </ul>
        </nav>
      </aside>
      <main className="flex-1">
        <div className="flex h-full">
          <div className="w-1/2 border-r">
            <div className="flex items-center p-4 bg-gray-200">
              <Input className="flex-1" placeholder="Search" type="search" />
            </div>
            <ScrollArea className="p-4 space-y-4" />
          </div>
          <div className="w-1/2">
            <div className="flex items-center justify-between p-4 bg-gray-200">
              <div className="flex space-x-2">
                <ArrowLeftIcon className="w-6 h-6 text-gray-600" />
                <ArrowRightIcon className="w-6 h-6 text-gray-600" />
              </div>
              <div className="flex space-x-2">
                <PrinterIcon className="w-6 h-6 text-gray-600" />
                <EllipsisVerticalIcon className="w-6 h-6 text-gray-600" />
              </div>
            </div>
            <div className="p-4 space-y-4">
              <div className="flex items-center space-x-4">
                <Avatar>
                  <AvatarImage alt="William Smith" src="/placeholder.svg?height=40&width=40" />
                  <AvatarFallback>WS</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="text-lg font-semibold">William Smith</h3>
                  <p className="text-sm text-gray-600">Meeting Tomorrow</p>
                  <p className="text-sm text-gray-400">Oct 22, 2023, 9:00 AM</p>
                </div>
              </div>
              <p className="text-gray-800">
                Hi, let's have a meeting tomorrow to discuss the project. I've been reviewing the project details and
                have some ideas I'd like to share. It's crucial that we align on our next steps to ensure the project's
                success.
              </p>
              <p className="text-gray-800">
                Please come prepared with any questions or insights you may have. Looking forward to our meeting!
              </p>
              <p className="text-gray-800">Best regards, William</p>
              <div className="flex justify-between">
                <Button variant="secondary">Mute this thread</Button>
                <Button>Send</Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>)
  );
}

function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function EllipsisVerticalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="1" />
      <circle cx="12" cy="5" r="1" />
      <circle cx="12" cy="19" r="1" />
    </svg>)
  );
}


function PrinterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
      <path d="M6 9V3a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v6" />
      <rect x="6" y="14" width="12" height="8" rx="1" />
    </svg>)
  );
}
